### ISSUE TITLE
[fix]: add key property to card component.

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/EventCalendar#11]
Add key property to card component. When you are rendering multiple equal components (in this case, the event card) you need to add a unique key to each one of them, that's because React needs to know how they are going to be treated in the virtual dom.
```jsx
<Card title={event.title} subTitle={event.date.start}>
  {event.description}
</Card>
```

**Comment by BSlaven** [comment]
Single event in the array as it is now does not have an ID, which is usually used as a unique identifier. Shall I use maybe the discription, and we can update it later on?

**Comment by EmmaDawsonDev** [comment]
The card component is no longer being used so this issue is no longer needed. Thanks for raising it though 😊
