### ISSUE TITLE
[feat]: Add link to Twitter 

### ISSUE THREAD

**Issue by WelshKaibigan** [EddieHubCommunity/EventCalendar#16]
Add a facility to post event information to Twitter when created

**Comment by suitupstan** [comment]
Like, get information from Twitter or post to twitter?

**Comment by WelshKaibigan** [comment]
When the event is created, also post it to Twitter

**Comment by suitupstan** [comment]
> When the event is created, also post it to Twitter

I don't think that is needed 😅
