### ISSUE TITLE
Change title of app.

### ISSUE THREAD

**Issue by NS007-dev** [EddieHubCommunity/EventCalendar#36]
Right now, the title of the app is `React App` and needs to be altered to Event Calendar / EddieHub Event Calendar.

**Comment by mohan-murali** [comment]
This is duplicate of #24

**Comment by NS007-dev** [comment]
Oh I just realised that, sorry for this duplicate issue. However I made a pr which is now merged not knowing that this is duplicate. @mohan-murali

**Comment by NS007-dev** [comment]
I just saw that I reviewed the original pr as well, yet I forgot, and made this.
