### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by suitupstan** [EddieHubCommunity/EventCalendar#43]
Add issue templates from the EddieBot/LinkFree repo.

**Comment by qwel-exe** [comment]
hey @krishguptadev you doing it or is it up to some one to take it ?

**Comment by suitupstan** [comment]
> hey @krishguptadev you doing it or is it up to some one to take it ?

Looking for a first-time contributor :) You already have a lot of 🟩s. Let's allow new contributors :D

**Comment by qwel-exe** [comment]
> lready have a lot of s. Let's allow new contributors :D

yep :)

**Comment by suitupstan** [comment]
Fixed in #51
