### ISSUE TITLE
Add Licence in README.md

### ISSUE THREAD

**Issue by syedsohan** [EddieHubCommunity/EventCalendar#46]
We should add LICENSE in README.md like we have in [LinkFree](https://github.com/EddieHubCommunity/LinkFree)
![License](https://user-images.githubusercontent.com/63908584/140694368-79320ef8-6668-4d8a-b9e6-a1e5a7b60353.png)

**Comment by thepranaygupta** [comment]
> 
> 
> We should add LICENSE in README.md like we have in [LinkFree](https://github.com/EddieHubCommunity/LinkFree) ![License](https://user-images.githubusercontent.com/63908584/140694368-79320ef8-6668-4d8a-b9e6-a1e5a7b60353.png)

I would like to work on this issue

**Comment by thepranaygupta** [comment]
@emmalearnscode @eddiejaoude should I propose the MIT License?

**Comment by EmmaDawsonDev** [comment]
> @emmalearnscode @eddiejaoude should I propose the MIT License?

Yes, it lists MIT in the about section already
