### ISSUE TITLE
Add Thanks to the all Contributors & Support in README.md

### ISSUE THREAD

**Issue by syedsohan** [EddieHubCommunity/EventCalendar#47]
We should add Thanks to the all Contributors & Support in README like [LinkFree](https://github.com/EddieHubCommunity/LinkFree)

![Thanks and Support](https://user-images.githubusercontent.com/63908584/140697009-905b59bb-630a-4424-9204-3cc00fb90fd0.png)

**Comment by thepranaygupta** [comment]
> 
> 
> We should add Thanks to the all Contributors & Support in README like [LinkFree](https://github.com/EddieHubCommunity/LinkFree)
> 
> ![Thanks and Support](https://user-images.githubusercontent.com/63908584/140697009-905b59bb-630a-4424-9204-3cc00fb90fd0.png)

I would like to work on this issue
