### ISSUE TITLE
Add Contributing Guideline

### ISSUE THREAD

**Issue by syedsohan** [EddieHubCommunity/EventCalendar#48]
We should add Contributing Guideline

**Comment by suitupstan** [comment]
Yep! Agreed! We can take the LinkFree guidelines as a starting point 😄

**Comment by thepranaygupta** [comment]
I would like to work on this issue 🙋🏻‍♂️

**Comment by suitupstan** [comment]
Sure @thepranaygupta! Feel free to work on it!
