### ISSUE TITLE
Spacing between font and icon should be given to look neat

### ISSUE THREAD

**Issue by atharvashirdhankar** [EddieHubCommunity/EventCalendar#49]
![IMG_20211108_130720](https://user-images.githubusercontent.com/72031540/140702244-54b3bd37-f91c-4106-80a2-9af2afed5c30.jpg)

Problem :
The text and GitHub icon almost overlap each other which are at left bottom side of the webpage.

**Comment by NeeshSamsi** [comment]
It seems there is a `p-mr-2` on the "Contribute on" `span` and the GH Icon but it's not applying in the browser. I am not familiar with Prime React so I am not sure what's going wrong.

**Comment by EmmaDawsonDev** [comment]
This has been fixed in pr 52.
