### ISSUE TITLE
Spacing under main navbar needs work.

### ISSUE THREAD

**Issue by BSlaven** [EddieHubCommunity/EventCalendar#58]
We should add some space under the navbar.

Two blue(ish) buttons on the right are literally touching the navbar, and the date text is too close as well.

Screenshot:
![Screenshot (40)](https://user-images.githubusercontent.com/55027209/141006022-cd336224-c452-42b4-a07b-9b569209c3a7.png)

**Comment by EmmaDawsonDev** [comment]
This issue has been fixed by another pull request
