### ISSUE TITLE
[docs]: quickstart guide

### ISSUE THREAD

**Issue by vikasganiga05** [EddieHubCommunity/EventCalendar#8]
Update the readme with a quickstart guide.

**Comment by EmmaDawsonDev** [comment]
There appears to be a quick start guide. Can you see if anything is missing?

**Comment by suitupstan** [comment]
@vikasganiga05 is there something we can help you with? 🙂

**Comment by vikasganiga05** [comment]
> There appears to be a quick start guide. Can you see if anything is missing?

Yes it LGTM :+1:  Thanks!

**Comment by vikasganiga05** [comment]
> @vikasganiga05 is there something we can help you with? slightly_smiling_face

Thanks! it LGTM :+1:

**Comment by vikasganiga05** [comment]
The readme is updated with a quick-start guide by @eddiejaoude . So, I am closing this issue :+1:

**Comment by suitupstan** [comment]
Awesome!
